name: "dbt_red_metropolitana"
version: "1.0.0"
config-version: 2

profile: "dbt_red_metropolitana"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_red_metropolitana:
    staging:
      +materialized: view
      +schema: silver

    silver:
      +materialized: table
      +schema: silver

    quarantine:
      +materialized: table
      +schema: quarantine

    gold:
      +materialized: table
      +schema: gold